### ISSUE TITLE
players can see staff chat on my server.

### ISSUE THREAD

**Issue by AlexPads** [Alemiz112/StarGate#2]
When I type in staff chat players can see it players, not in the bungee config.

**Comment by Alemiz112** [comment]
"players can see it players" - What do you mean ?
And send how is your perms configurated.

**Comment by AlexPads** [comment]
This is my Config.

```
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.send
  - bungeecord.command.ip
  - stargate.staffchat
  - stargate.staff
timeout: 30000
log_commands: false
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    raknet: true
    motd: '&1Just another Waterfall - Forced Host'
    transfer_group: default
    address: hub.saltypixel.ga:19157
    restricted: false
  SkyBlock:
    raknet: true
    motd: '&1Just another Waterfall - Forced Host'
    transfer_group: default
    address: hub.saltypixel.ga:19155
    restricted: false
listeners:
- query_port: 19132
  motd: '&l&4Salty&1Pixel&bPE &aHub! '
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    hub.saltypixel.ga: lobby
  ping_passthrough: false
  raknet: true
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 250
  tab_size: 60
  force_default_server: false
ip_forward: false
network_compression_threshold: 256
prevent_proxy_connections: false
groups:
  AlexPads:
  - admin
  MistakingManx49:
  - admin
  saltygoat420:
  - admin
  iamfatman65888:
  - admin
  BenjiplaysMc:
  - admin
connection_throttle: 4000
stats: 1aefdf93-278a-4c7f-bef3-7567686a2d21
connection_throttle_limit: 3
log_pings: true
```

and I mean players that do not have admin can see the staff chat.
